# Generated by Django 3.2.8 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='date',
            field=models.DateField(verbose_name='Date Played'),
        ),
    ]
